main: pb.ajneb97.PaintballBattle
version: 1.12.3
name: PaintballBattle
api-version: 1.13
author: Ajneb97
softdepend: [Multiverse-Core, HolographicDisplays, Vault, PlaceholderAPI, DecentHolograms]
// TODO: Remove Holographic displays

commands:
  paintball:
    description: Main command of PaintballBattle
    aliases: pb